name: Access Secret in Code

on: 
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Python Script
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
